openapi: "3.0.3"
info:
  title: Hangman Backend API
  version: "1.0.1"
  description: |
    RESTful API for Hangman game user management.

    ## Authentication
    All endpoints require JWT Bearer token in Authorization header when authentication is required:
    ```
    Authorization: Bearer <your-jwt-token>
    ```

    ## Rate Limiting
    Different endpoints have different rate limits per minute:
    - **Strict operations** (DELETE): 10 requests/minute
    - **Gameplay operations**: 60 requests/minute
    - **Read operations** (GET): 300 requests/minute
    - **Write operations** (PATCH): 60 requests/minute

    When rate limit is exceeded, API returns 429 status code.

    ## Soft Delete
    Deleted profiles return 404 but data is retained with `deleted_at` timestamp.
    Valid JWT tokens remain active after profile deletion.

servers:
  - url: https://localhost:5000/
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    Unauthorized:
      description: Authentication failed/required
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: "UNAUTHORIZED"
            message: "Invalid or expired authentication token"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: "NOT_FOUND"
            message: "The requested resource does not exist or has been deleted"

    TooManyRequests:
      description: Too many requests
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: "RATE_LIMIT_EXCEEDED"
            message: "Too many requests. Please try again in 60 seconds"

    BadRequest:
      description: Invalid request data
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: "VALIDATION_ERROR"
            message: "Invalid input data"

  schemas:
    Me:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        role:
          type: string
          enum: ["authenticated", "anon"]
          example: "authenticated"
    Profile:
      type: object
      required:
        - id
        - email
        - username
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        username:
          type: string
          description: Display name
          minLength: 3
          maxLength: 30
          pattern: "^[a-zA-Z0-9_-]+$"
          example: "player_12345"
        pfp:
          type: string
          format: uri
          description: Profile picture URL
          maxLength: 2048
          example: "https://xsyzxrwyabxqsgjyhult.supabase.co/storage/v1/object/public/profile_pictures/default.png"
        status:
          type: string
          example: "online"
        created_at:
          type: string
          format: date-time
          description: Profile creation timestamp
          example: "2026-01-05T10:30:00Z"

    Error:
      type: object
      description: Standard Error Response
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: "VALIDATION_ERROR"
        message:
          type: string
          example: "Invalid input data provided"

paths:
  /me:
    get:
      summary: Get current authenticated user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Authenticated user identity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Me"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "429":
          $ref: "#/components/responses/TooManyRequests"
  /profile:
    get:
      summary: View profile of the authenticated user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Profile fetched successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "429":
          $ref: "#/components/responses/TooManyRequests"
    patch:
      summary: Update authenticated user profile
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 30
                  pattern: "^[a-zA-Z0-9_-]+$"
                pfp:
                  type: string
                  format: uri
                  maxLength: 2048
                status:
                  type: string
      responses:
        "200":
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          description: Conflict - username already taken
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "429":
          $ref: "#/components/responses/TooManyRequests"
    delete:
      summary: Delete authenticated user profile
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Profile deleted successfully
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
